name: Build and Release APK

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create stable debug keystore
      run: |
        echo "Creating debug keystore..."
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
        echo "Debug keystore created successfully"
        ls -la debug.keystore
        cp debug.keystore app/
        echo "Debug keystore copied to app directory"
        ls -la app/debug.keystore
      
    - name: Build Debug APK
      run: |
        echo "Building APK..."
        ./gradlew assembleDebug --info
        echo "APK built successfully"
        ls -la app/build/outputs/apk/debug/
      
    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} \
          --title "CZp ${{ github.ref_name }}" \
          --notes "## Что нового в версии ${{ github.ref_name }}
        
        ### Изменения:
        - Автоматическая сборка и публикация
        - Улучшенная система обновлений
        
        ### Установка:
        1. Скачайте APK файл
        2. Разрешите установку из неизвестных источников
        3. Установите приложение
        
        ### Примечание:
        Это стабильная версия приложения." \
          --repo ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload APK to Release
      run: |
        cp ./app/build/outputs/apk/debug/app-debug.apk ./CZp-${{ github.ref_name }}.apk
        gh release upload ${{ github.ref_name }} \
          ./CZp-${{ github.ref_name }}.apk \
          --repo ${{ github.repository }} \
          --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 